### ISSUE TITLE
Why does this require nightly?

### ISSUE THREAD

**Issue by m4b** [luser/spawn-ptrace#1]
Haven't investigated, but would it be possible to get this off of nightly any time soon?

Thanks!

**Comment by luser** [comment]
Oh yeah! It uses [`CommandExt::before_exec`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.before_exec) which stabilized in 1.15. I wrote this crate before that had shipped, so I literally just need to update the README.

**Comment by luser** [comment]
I updated the README and cleaned it up a little while I was there. I also removed the dependency on `skeptic` so users of this crate don't get stuck building it, in favor of a hand-written test to run rustdoc on `README.md`. I published a new version (0.1.1) with those changes. Thanks for the prodding!

**Comment by m4b** [comment]
Awesome thanks !
